server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      '[hibernate.format_sql]': true


logging:
  level:  
    root: DEBUG
    '[org.springframework.boot.autoconfigure]': ERROR
